build:
    image: golang:1.5
    environment:
        - GO15VENDOREXPERIMENT=1
    commands:
        - go get
        - go build
        - go test
    compose:
        cache:
            image: redis
